### ISSUE TITLE
What about self-closing tags?

### ISSUE THREAD

**Issue by blake-regalia** [snappyjs/node-xml-stream#4]
It seems there is no indication given when a tag is self-closing, only an `opentag` event is emitted with no flags and no `closetag` event to follow. Kinda an irritating bug to have to discover, and the documentation doesn't seem to warn about it either?

**Comment by blake-regalia** [comment]
For anyone else stumbling across this thread, someone already forked for this exact reason and you can just use this drop-in replacement: https://github.com/mfahlandt/node-xml-stream-parser

**Comment by snappyjs** [comment]
Sorry @blake-regalia I haven't been around for a while! But now I'm back.

This issue is now merged to this package also if you are still interested in it! Thank you for the comment!
