### ISSUE TITLE
Out of memory on big xml files.

### ISSUE THREAD

**Issue by cheluskin** [snappyjs/node-xml-stream#5]
Node kill execution with "Killed" message in console. XML file size > 1G and machine memory 1 GB.

```
const parser = xmlToJson();
const parserStream = parser.createStream();
const fileContent = FS.createReadStream('tmp/' + config.needFileinArchive);
const writeStream = FS.createWriteStream("tmp/" + config.needFileinArchive + '.json');
fileContent.pipe(parserStream).pipe(writeStream).on("close", (err) => {
    if (err) {
        console.error("Error on convert file to json", err);
        return;
    }
    console.log("File converted to json");
    FS.unlink('tmp/' + config.needFileinArchive, (err) => {
        if (err) console.log("Error on file remove", err);
    });
})
```

on files with size ~ 40mb works great

**Comment by snappyjs** [comment]
Sorry for the late reply! I haven't been very active latley do to work. But now I'm back. 

The xmlToJson package that you are using - won't will that read all of the content to memory?
I can't see where in your code you are listening to any of the events from the node-xml-stream either?

If the xmlToJson() parser reads everything in-memory than you will get issues there. But the node-xml-stream does not save anything in-memory it just sends out the events and forgets about it.
